import { inchesToSixteenths } from '../geometry/units';
import type {
  CabinetDefinition,
  DoorStyleOption,
  DrawerBoxOption,
  FinishOption,
  HardwareOption,
  HingeOption,
} from './types';

export const FINISH_OPTIONS: FinishOption[] = [
  {
    id: 'polar_white',
    name: 'Polar White (Satin)',
    colorHex: '#F5F5F5',
    roughness: 0.25,
  },
  {
    id: 'natural_oak',
    name: 'Natural White Oak',
    colorHex: '#D4B38C',
    roughness: 0.5,
    woodGrain: true,
  },
  {
    id: 'matte_navy',
    name: 'Deep Nautical Navy',
    colorHex: '#1E2D42',
    roughness: 0.35,
  },
  {
    id: 'charcoal_slate',
    name: 'Charcoal Slate',
    colorHex: '#33383F',
    roughness: 0.3,
  },
  {
    id: 'sage_green',
    name: 'Eucalyptus Sage',
    colorHex: '#7D8C7C',
    roughness: 0.4,
  },
];
export const INTERIOR_FINISH_OPTIONS: FinishOption[] = [
  {
    id: 'natural_birch',
    name: 'Natural Maple / Birch (Plywood)',
    colorHex: '#EFE3D3',
    roughness: 0.45,
    woodGrain: true,
  },
  {
    id: 'white_melamine',
    name: 'Crisp White Melamine',
    colorHex: '#F8F9FA',
    roughness: 0.2,
  },
  {
    id: 'matching_oak',
    name: 'Matching Natural White Oak',
    colorHex: '#D4B38C',
    roughness: 0.5,
    woodGrain: true,
  },
  {
    id: 'slate_linen',
    name: 'Slate Linen Texture',
    colorHex: '#4A525D',
    roughness: 0.4,
  },
];

export const DOOR_STYLES: DoorStyleOption[] = [
  {
    id: 'shaker',
    name: 'Classic Shaker (2.5" Stiles)',
    stileWidthInches: 2.5,
    bevelDepthInches: 0.25,
  },
  {
    id: 'slab_modern',
    name: 'Modern Flat Slab',
    stileWidthInches: 0,
    bevelDepthInches: 0,
  },
  {
    id: 'raised_panel',
    name: 'Traditional Raised Panel',
    stileWidthInches: 2.75,
    bevelDepthInches: 0.375,
  },
];

export const HARDWARE_OPTIONS: HardwareOption[] = [
  {
    id: 'matte_black_bar',
    name: '5" Matte Black Bar Pull',
    type: 'pull',
    primitive: 'box',
    widthInches: 0.5,
    heightInches: 5,
    depthInches: 1.25,
    colorHex: '#1D1D1F',
    metalness: 0.7,
  },
  {
    id: 'brushed_brass_bar',
    name: '5" Brushed Brass Bar Pull',
    type: 'pull',
    primitive: 'box',
    widthInches: 0.5,
    heightInches: 5,
    depthInches: 1.25,
    colorHex: '#D4AF37',
    metalness: 0.85,
  },
  {
    id: 'satin_nickel_bar',
    name: '5" Satin Nickel Bar Pull',
    type: 'pull',
    primitive: 'box',
    widthInches: 0.5,
    heightInches: 5,
    depthInches: 1.25,
    colorHex: '#C0C0C0',
    metalness: 0.8,
  },
  {
    id: 'modern_knob',
    name: '1.25" Minimalist Round Knob',
    type: 'knob',
    primitive: 'cylinder',
    widthInches: 1.25,
    heightInches: 1.25,
    depthInches: 1.25,
    radiusInches: 0.625,
    colorHex: '#1D1D1F',
    metalness: 0.75,
  },
  {
    id: 'no_hardware',
    name: 'No hardware',
    type: 'none',
    primitive: 'box',
    widthInches: 0,
    heightInches: 0,
    depthInches: 0,
    colorHex: '#1D1D1F',
    metalness: 0,
  },
  {
    id: 'matte_black_cup_pull',
    name: '3" Matte Black Cup Pull',
    type: 'cup_pull',
    primitive: 'box',
    widthInches: 3,
    heightInches: 1.25,
    depthInches: 0.75,
    colorHex: '#1D1D1F',
    metalness: 0.7,
  },
  {
    id: 'brushed_brass_edge_pull',
    name: '4" Brushed Brass Edge Pull',
    type: 'edge_pull',
    primitive: 'box',
    widthInches: 4,
    heightInches: 0.5,
    depthInches: 1,
    colorHex: '#D4AF37',
    metalness: 0.85,
  },
];

export const DRAWER_BOX_OPTIONS: DrawerBoxOption[] = [
  {
    id: 'dovetail_soft_close',
    name: 'Solid Birch Dovetail (Soft-Close Undermount)',
    slideType: 'undermount_soft_close',
    material: 'solid_wood_dovetail',
    weightCapacityLbs: 100,
    extensionType: 'full_extension',
    description:
      '5/8" solid birch dovetail drawer box with synchronized Blumotion soft-close undermount slides.',
  },
  {
    id: 'metal_box_slim',
    name: 'Slim Metal Double-Wall Box (Soft-Close)',
    slideType: 'undermount_soft_close',
    material: 'metal_box_slim',
    weightCapacityLbs: 110,
    extensionType: 'full_extension',
    description:
      'Modern 13mm thin metal double-wall drawer system with integrated rack-and-pinion synchronization.',
  },
  {
    id: 'push_to_open_undermount',
    name: 'Handleless Push-to-Open (Full Extension)',
    slideType: 'push_to_open',
    material: 'solid_wood_dovetail',
    weightCapacityLbs: 85,
    extensionType: 'full_extension',
    description:
      'Mechanical tip-on push-to-open latch mechanism for minimalist hardware-free cabinet fronts.',
  },
  {
    id: 'standard_side_mount',
    name: 'Standard Plywood (Side-Mount Ball-Bearing)',
    slideType: 'side_mount_ball_bearing',
    material: 'plywood_standard',
    weightCapacityLbs: 75,
    extensionType: 'full_extension',
    description: 'Classic durable ball-bearing side runners with 1/2" plywood box construction.',
  },
];

export const HINGE_OPTIONS: HingeOption[] = [
  {
    id: 'euro_110_soft_close',
    name: '110° Clip-On Concealed Hinge (Soft-Close)',
    openingAngleDegrees: 110,
    mountingType: 'concealed_soft_close',
    softClose: true,
    description:
      'Standard 35mm cup European clip-on concealed hinge with 6-way cam adjustment and integrated soft-close.',
  },
  {
    id: 'wide_angle_165',
    name: '165° Wide-Angle Zero-Protrusion Hinge',
    openingAngleDegrees: 165,
    mountingType: 'wide_angle_165',
    softClose: true,
    description:
      'Wide-angle opening for pantry pull-out drawers and corner clearance with zero inner door protrusion.',
  },
  {
    id: 'pie_corner_bifold',
    name: 'Pie-Corner Bi-Fold Lazy Susan Hinge',
    openingAngleDegrees: 60,
    mountingType: 'pie_corner_bifold',
    softClose: false,
    description:
      'Specialized articulating bi-fold hinge joining dual doors on L-shaped corner base cabinets.',
  },
  {
    id: 'face_frame_compact',
    name: 'Compact 3/4" Overlay Face-Frame Hinge',
    openingAngleDegrees: 105,
    mountingType: 'face_frame_compact',
    softClose: true,
    description:
      'One-piece compact mounting hinge designed for traditional face-frame cabinet edge attachment.',
  },
];

export const STANDARD_CABINET_CATALOG: CabinetDefinition[] = [
  // ==================== BASE CABINETS (Standard 34.5"H x 24"D) ====================
  {
    id: 'B12',
    code: 'B12',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '12" Standard Base Cabinet',
    category: 'base',
    description: 'Single full door with 1 adjustable shelf and top drawer.',
    nominalWidthInches: 12,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(12),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'right',
    hasDrawers: true,
    drawerCount: 1,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B12',
      sku: '1004128912',
      estimatedPriceUSD: 149.0,
      productUrl: 'https://www.homedepot.com/s/B12%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'B15',
    code: 'B15',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '15" Standard Base Cabinet',
    category: 'base',
    description: 'Single full door with 1 adjustable shelf and 1 top drawer.',
    nominalWidthInches: 15,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(15),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'right',
    hasDrawers: true,
    drawerCount: 1,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B15',
      sku: '1004128915',
      estimatedPriceUSD: 159.0,
      productUrl: 'https://www.homedepot.com/s/B15%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'B18',
    code: 'B18',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '18" Standard Base Cabinet',
    category: 'base',
    description: 'Single full door with 1 adjustable shelf and 1 top drawer.',
    nominalWidthInches: 18,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(18),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'right',
    hasDrawers: true,
    drawerCount: 1,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B18',
      sku: '1004128918',
      estimatedPriceUSD: 169.0,
      productUrl: 'https://www.homedepot.com/s/B18%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'B24',
    code: 'B24',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '24" Standard Base Cabinet',
    category: 'base',
    description: 'Double doors with 1 adjustable shelf and 1 full-width top drawer.',
    nominalWidthInches: 24,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(24),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: true,
    drawerCount: 1,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B24',
      sku: '1004128924',
      estimatedPriceUSD: 189.0,
      productUrl: 'https://www.homedepot.com/s/B24%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'B30',
    code: 'B30',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '30" Standard Base Cabinet',
    category: 'base',
    description: 'Double doors with 1 adjustable shelf and 2 side-by-side top drawers.',
    nominalWidthInches: 30,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: true,
    drawerCount: 2,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B30',
      sku: '1004128930',
      estimatedPriceUSD: 209.0,
      productUrl: 'https://www.homedepot.com/s/B30%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'B36',
    code: 'B36',
    source: 'stock',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '36" Standard Base Cabinet',
    category: 'base',
    description: 'Double doors with 1 adjustable shelf and 2 side-by-side top drawers.',
    nominalWidthInches: 36,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(36),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: true,
    drawerCount: 2,
    shelfCount: 1,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Stock Base Cabinet B36',
      sku: '1004128936',
      estimatedPriceUSD: 239.0,
      productUrl: 'https://www.homedepot.com/s/B36%20shaker%20cabinet',
      isVerifiedSample: true,
    },
  },

  // ==================== SINK BASE CABINETS ====================
  {
    id: 'SB30',
    code: 'SB30',
    source: 'stock',
    family: 'sink_base',
    frontLayout: 'false_front',
    name: '30" Sink Base Cabinet',
    category: 'base',
    description: 'Double doors with open top cavity for drop-in or undermount sink plumbing.',
    nominalWidthInches: 30,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 0,
    hasSinkCutout: true,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Sink Base SB30',
      sku: '1004130030',
      estimatedPriceUSD: 199.0,
      productUrl: 'https://www.homedepot.com/s/SB30%20sink%20base',
      isVerifiedSample: true,
    },
  },
  {
    id: 'SB36',
    code: 'SB36',
    source: 'stock',
    family: 'sink_base',
    frontLayout: 'false_front',
    name: '36" Sink Base Cabinet',
    category: 'base',
    description: 'Double doors with wide cavity for dual bowl kitchen sinks and disposal.',
    nominalWidthInches: 36,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(36),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 0,
    hasSinkCutout: true,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Sink Base SB36',
      sku: '1004130036',
      estimatedPriceUSD: 219.0,
      productUrl: 'https://www.homedepot.com/s/SB36%20sink%20base',
      isVerifiedSample: true,
    },
  },

  // ==================== 3-DRAWER BASE CABINETS ====================
  {
    id: 'DB18',
    code: 'DB18',
    source: 'stock',
    family: 'drawer_base',
    frontLayout: 'drawers',
    name: '18" 3-Drawer Base Cabinet',
    category: 'base',
    description: '3 tiered drawers: 1 standard cutlery drawer + 2 deep storage drawers.',
    nominalWidthInches: 18,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(18),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'drawers',
    hasDrawers: true,
    drawerCount: 3,
    shelfCount: 0,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker 3-Drawer Base DB18',
      sku: '1004140018',
      estimatedPriceUSD: 249.0,
      productUrl: 'https://www.homedepot.com/s/DB18%20drawer%20base',
      isVerifiedSample: true,
    },
  },
  {
    id: 'DB24',
    code: 'DB24',
    source: 'stock',
    family: 'drawer_base',
    frontLayout: 'drawers',
    name: '24" 3-Drawer Base Cabinet',
    category: 'base',
    description: '3 tiered drawers for pots, pans, and kitchen utensils.',
    nominalWidthInches: 24,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(24),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'drawers',
    hasDrawers: true,
    drawerCount: 3,
    shelfCount: 0,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker 3-Drawer Base DB24',
      sku: '1004140024',
      estimatedPriceUSD: 279.0,
      productUrl: 'https://www.homedepot.com/s/DB24%20drawer%20base',
      isVerifiedSample: true,
    },
  },

  // ==================== WALL UPPER CABINETS (Standard 12"D) ====================
  {
    id: 'W1530',
    code: 'W1530',
    source: 'stock',
    family: 'wall',
    frontLayout: 'single_door',
    name: '15"W x 30"H Wall Cabinet',
    category: 'wall',
    description: 'Single door wall cabinet with 2 adjustable shelves.',
    nominalWidthInches: 15,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(15),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'right',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Wall Cabinet W1530',
      sku: '1004150015',
      estimatedPriceUSD: 119.0,
      productUrl: 'https://www.homedepot.com/s/W1530%20wall%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'W2430',
    code: 'W2430',
    source: 'stock',
    family: 'wall',
    frontLayout: 'double_door',
    name: '24"W x 30"H Wall Cabinet',
    category: 'wall',
    description: 'Double door wall cabinet with 2 adjustable shelves.',
    nominalWidthInches: 24,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(24),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Wall Cabinet W2430',
      sku: '1004150024',
      estimatedPriceUSD: 139.0,
      productUrl: 'https://www.homedepot.com/s/W2430%20wall%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'W3030',
    code: 'W3030',
    source: 'stock',
    family: 'wall',
    frontLayout: 'double_door',
    name: '30"W x 30"H Wall Cabinet',
    category: 'wall',
    description: 'Double door wall cabinet with 2 adjustable shelves.',
    nominalWidthInches: 30,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Wall Cabinet W3030',
      sku: '1004150030',
      estimatedPriceUSD: 154.0,
      productUrl: 'https://www.homedepot.com/s/W3030%20wall%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'W3630',
    code: 'W3630',
    source: 'stock',
    family: 'wall',
    frontLayout: 'double_door',
    name: '36"W x 30"H Wall Cabinet',
    category: 'wall',
    description: 'Double door wide wall cabinet with 2 adjustable shelves.',
    nominalWidthInches: 36,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(36),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Wall Cabinet W3630',
      sku: '1004150036',
      estimatedPriceUSD: 179.0,
      productUrl: 'https://www.homedepot.com/s/W3630%20wall%20cabinet',
      isVerifiedSample: true,
    },
  },
  {
    id: 'W3036',
    code: 'W3036',
    source: 'stock',
    family: 'wall',
    frontLayout: 'double_door',
    name: '30"W x 36"H Wall Cabinet',
    category: 'wall',
    description: 'Double door tall wall cabinet with 3 adjustable shelves.',
    nominalWidthInches: 30,
    nominalHeightInches: 36,
    nominalDepthInches: 12,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(36),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 3,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Wall Cabinet W3036',
      sku: '1004150031',
      estimatedPriceUSD: 169.0,
      productUrl: 'https://www.homedepot.com/s/W3036%20wall%20cabinet',
      isVerifiedSample: true,
    },
  },

  // ==================== TALL PANTRY CABINETS ====================
  {
    id: 'U2484',
    code: 'U2484',
    source: 'stock',
    family: 'tall',
    frontLayout: 'single_door',
    name: '24"W x 84"H Tall Utility / Pantry Cabinet',
    category: 'tall',
    description: 'Floor-to-ceiling pantry with 4 adjustable shelves and dual door sections.',
    nominalWidthInches: 24,
    nominalHeightInches: 84,
    nominalDepthInches: 24,
    width: inchesToSixteenths(24),
    height: inchesToSixteenths(84),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'right',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 4,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Pantry U2484',
      sku: '1004160024',
      estimatedPriceUSD: 389.0,
      productUrl: 'https://www.homedepot.com/s/U2484%20pantry%20cabinet',
      isVerifiedSample: true,
    },
  },

  // ==================== CORNER CABINETS ====================
  {
    id: 'LS36',
    code: 'LS36',
    source: 'stock',
    family: 'lazy_susan_corner',
    frontLayout: 'double_door',
    name: '36" Lazy Susan Corner Base Cabinet',
    category: 'corner',
    description: 'L-corner base cabinet with rotating dual chrome wire baskets.',
    nominalWidthInches: 36,
    nominalHeightInches: 34.5,
    nominalDepthInches: 36,
    width: inchesToSixteenths(36),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(36),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay Hampton Satin White Shaker Corner Base LS36',
      sku: '1004170036',
      estimatedPriceUSD: 329.0,
      productUrl: 'https://www.homedepot.com/s/LS36%20lazy%20susan',
      isVerifiedSample: true,
    },
  },

  // ==================== FILLERS & TRIMS ====================
  {
    id: 'F330',
    code: 'F330',
    source: 'stock',
    family: 'filler',
    frontLayout: 'open',
    name: '3" x 30" Wall Cabinet Filler Strip',
    category: 'filler',
    description: 'Solid wood color-matched filler strip for wall gaps and clearance.',
    nominalWidthInches: 3,
    nominalHeightInches: 30,
    nominalDepthInches: 0.75,
    width: inchesToSixteenths(3),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(0.75),
    defaultDoorSwing: 'open_shelf',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 0,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay 3 in. W x 30 in. H Cabinet Filler',
      sku: '1004180030',
      estimatedPriceUSD: 21.0,
      productUrl: 'https://www.homedepot.com/s/3x30%20cabinet%20filler',
      isVerifiedSample: true,
    },
  },
  {
    id: 'F334',
    code: 'F334',
    source: 'stock',
    family: 'filler',
    frontLayout: 'open',
    name: '3" x 34.5" Base Cabinet Filler Strip',
    category: 'filler',
    description: 'Solid wood color-matched filler strip for base cabinet wall runs.',
    nominalWidthInches: 3,
    nominalHeightInches: 34.5,
    nominalDepthInches: 0.75,
    width: inchesToSixteenths(3),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(0.75),
    defaultDoorSwing: 'open_shelf',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 0,
    retailMapping: {
      retailer: 'Home Depot',
      productName: 'Hampton Bay 3 in. W x 34.5 in. H Base Cabinet Filler',
      sku: '1004180034',
      estimatedPriceUSD: 24.0,
      productUrl: 'https://www.homedepot.com/s/3x34.5%20cabinet%20filler',
      isVerifiedSample: true,
    },
  },
  {
    id: 'DB30',
    code: 'DB30',
    source: 'stock',
    family: 'drawer_base',
    frontLayout: 'drawers',
    name: '30" 3-Drawer Base Cabinet',
    category: 'base',
    description: 'Three full-width drawers for pots, pans, and utensils.',
    nominalWidthInches: 30,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'drawers',
    hasDrawers: true,
    drawerCount: 3,
    shelfCount: 0,
  },
  {
    id: 'W1830',
    code: 'W1830',
    source: 'stock',
    family: 'wall',
    frontLayout: 'single_door',
    name: '18"W x 30"H Wall Cabinet',
    category: 'wall',
    description: 'Single-door wall cabinet with two adjustable shelves.',
    nominalWidthInches: 18,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(18),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'right',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
  },
  {
    id: 'W3015',
    code: 'W3015',
    source: 'stock',
    family: 'appliance_bridge',
    frontLayout: 'double_door',
    name: '30"W x 15"H Appliance Bridge Cabinet',
    category: 'wall',
    description: 'Shallow-height double-door cabinet for installation above an appliance.',
    nominalWidthInches: 30,
    nominalHeightInches: 15,
    nominalDepthInches: 24,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(15),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 1,
  },
  {
    id: 'CB30',
    code: 'CB30',
    source: 'built_template',
    family: 'standard_base',
    frontLayout: 'door_and_drawer',
    name: '30" Custom Base Cabinet',
    category: 'base',
    description: 'Editable built base with one drawer and one shelf.',
    nominalWidthInches: 30,
    nominalHeightInches: 34.5,
    nominalDepthInches: 24,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(34.5),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: true,
    drawerCount: 1,
    shelfCount: 1,
  },
  {
    id: 'CW30',
    code: 'CW30',
    source: 'built_template',
    family: 'wall',
    frontLayout: 'double_door',
    name: '30" Custom Wall Cabinet',
    category: 'wall',
    description: 'Editable built wall cabinet with two shelves.',
    nominalWidthInches: 30,
    nominalHeightInches: 30,
    nominalDepthInches: 12,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(30),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 2,
  },
  {
    id: 'CT24',
    code: 'CT24',
    source: 'built_template',
    family: 'tall',
    frontLayout: 'double_door',
    name: '24" Custom Tall Cabinet',
    category: 'tall',
    description: 'Editable full-height built cabinet with four shelves.',
    nominalWidthInches: 24,
    nominalHeightInches: 84,
    nominalDepthInches: 24,
    width: inchesToSixteenths(24),
    height: inchesToSixteenths(84),
    depth: inchesToSixteenths(24),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 4,
  },
  {
    id: 'BK30',
    code: 'BK30',
    source: 'built_template',
    family: 'bookcase',
    frontLayout: 'open',
    name: '30" Built Bookcase',
    category: 'tall',
    description: 'Open built-in bookcase with five shelves.',
    nominalWidthInches: 30,
    nominalHeightInches: 84,
    nominalDepthInches: 12,
    width: inchesToSixteenths(30),
    height: inchesToSixteenths(84),
    depth: inchesToSixteenths(12),
    defaultDoorSwing: 'open_shelf',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 5,
  },
  {
    id: 'BN48',
    code: 'BN48',
    source: 'built_template',
    family: 'bench',
    frontLayout: 'drawers',
    name: '48" Built Bench',
    category: 'base',
    description: 'Low built-in bench with two wide drawers.',
    nominalWidthInches: 48,
    nominalHeightInches: 18,
    nominalDepthInches: 20,
    width: inchesToSixteenths(48),
    height: inchesToSixteenths(18),
    depth: inchesToSixteenths(20),
    defaultDoorSwing: 'drawers',
    hasDrawers: true,
    drawerCount: 2,
    shelfCount: 0,
  },
  {
    id: 'MB48',
    code: 'MB48',
    source: 'built_template',
    family: 'media',
    frontLayout: 'double_door',
    name: '48" Built Media Base',
    category: 'base',
    description: 'Low built media cabinet with double doors and one shelf.',
    nominalWidthInches: 48,
    nominalHeightInches: 24,
    nominalDepthInches: 18,
    width: inchesToSixteenths(48),
    height: inchesToSixteenths(24),
    depth: inchesToSixteenths(18),
    defaultDoorSwing: 'double',
    hasDrawers: false,
    drawerCount: 0,
    shelfCount: 1,
  },
];

/**
 * Finds a cabinet definition in the catalog by code (e.g. 'B30').
 */
export function getCabinetDefinitionByCode(code: string): CabinetDefinition | undefined {
  return STANDARD_CABINET_CATALOG.find((c) => c.code.toUpperCase() === code.toUpperCase());
}

/**
 * Filter catalog by category.
 */
export function getCabinetsByCategory(category: string): CabinetDefinition[] {
  if (category === 'all') return STANDARD_CABINET_CATALOG;
  return STANDARD_CABINET_CATALOG.filter((c) => c.category === category);
}
